'use client';
import { useId } from 'react';
import { MultiField, ProfileSection, SelectField, TextField } from './ProfileFields';
import { benefitOptions, employeeSizes, employerSteps, hasDuplicates, organizationCatalogs as c, organizationTypes, type Draft } from '@/lib/organizations/frontend';
import type { OrganizationContext } from '@/lib/organizations/contracts';

export function TextEntries({ title, values, onChange, limit = 200, maximum }: { title: string; values: string[]; onChange: (values: string[]) => void; limit?: number; maximum?: number }) {
  const duplicate = hasDuplicates(values.map(v => v.trim()).filter(Boolean));
  return <fieldset className="profile-multi employer-entries"><legend>{title}</legend>{values.map((value, i) => <div className="employer-entry" key={i}><TextField title={`${title} ${i + 1}`} value={value} error={duplicate && value.trim() ? 'Pašalinkite pasikartojančias reikšmes.' : undefined} maxLength={limit} onChange={v => onChange(values.map((old, n) => n === i ? v : old))} /><button className="profile-button danger" type="button" aria-label={`Pašalinti: ${title} ${i + 1}`} onClick={() => onChange(values.filter((_, n) => n !== i))}>Pašalinti</button></div>)}<button type="button" className="profile-button secondary" disabled={maximum !== undefined && values.length >= maximum} onClick={() => onChange([...values, ''])}>Pridėti</button></fieldset>;
}
export function EmployerLegalFields({ value, onChange, locked = false }: { value: Pick<Draft, 'legalName' | 'legalForm' | 'legalCode'>; onChange: (patch: Partial<Draft>) => void; locked?: boolean }) {
  const form = c.legalForms.find(([code]) => code === value.legalForm);
  return <><TextField title={['natural_person','individual_activity'].includes(value.legalForm) ? 'Juridinis pavadinimas / vardas ir pavardė' : 'Juridinis pavadinimas'} value={value.legalName} maxLength={200} readOnly={locked} onChange={v => onChange({ legalName: v })} /><SelectField title="Teisinė forma" options={c.legalForms.map(([code, label]) => ({ code: String(code), label_lt: String(label) }))} value={value.legalForm} disabled={locked} onChange={v => onChange({ legalForm: v })} /><TextField title="Juridinio asmens kodas" optional={form?.[2] === false} value={value.legalCode} maxLength={64} readOnly={locked} onChange={v => onChange({ legalCode: v })} /></>;
}
export function EmployerRepresentativeFields({ value, onChange }: { value: Pick<Draft, 'firstName' | 'lastName' | 'capacity' | 'privatePhone'>; onChange: (patch: Partial<Draft>) => void }) {
  return <><div className="profile-grid"><TextField title="Vardas" value={value.firstName} maxLength={100} onChange={v => onChange({ firstName: v })} /><TextField title="Pavardė" value={value.lastName} maxLength={100} onChange={v => onChange({ lastName: v })} /></div><TextField title="Atstovavimo pagrindas / pareigos" value={value.capacity} maxLength={200} onChange={v => onChange({ capacity: v })} /><TextField title="Kontaktinis telefonas" type="tel" value={value.privatePhone} maxLength={40} onChange={v => onChange({ privatePhone: v })} /></>;
}
export function EmployerActivityFields({ draft, onChange }: { draft: Draft; onChange: (patch: Partial<Draft>) => void }) {
  const groups = c.groups.filter(g => g.type === draft.type).sort((a, b) => a.order - b.order);
  return <>{groups.map(g => {
    const stored = draft.groups.find(value => value.group_code === g.code) ?? { group_code: g.code, options: [], custom: [] };
    const update = (patch: Partial<typeof stored>) => onChange({ groups: [...draft.groups.filter(value => value.group_code !== g.code), { ...stored, ...patch }] });
    const choices = c.options.filter(o => o.type === draft.type && o.group === g.code).sort((a, b) => a.order - b.order).map(o => ({ code: o.code, label_lt: o.label }));
    return <div key={`${draft.type}:${g.code}`} className="employer-activity-group">{g.kind === 'choice' && <MultiField title={g.label} value={stored.options} options={choices} compact={false} onChange={v => update({ options: v, custom: v.includes('other') ? stored.custom : [] })} />}{(g.kind === 'text' || stored.options.includes('other')) && <TextEntries title={g.kind === 'text' ? g.label : `${g.label}: kita`} values={stored.custom} onChange={v => update({ custom: v })} />}</div>;
  })}</>;
}
export default function EmployerProfileFields({ step, draft, context, disabled, onChange, onTypeChange, onLegalChange, media }: { step: number; draft: Draft; context: OrganizationContext; disabled: boolean; onChange: (patch: Partial<Draft>) => void; onTypeChange: (value: string) => void; onLegalChange: () => void; media: React.ReactNode }) {
  const descriptionId = useId();
  const canEdit = context.capabilities.canEditProfile;
  const canRepresentative = context.capabilities.canSubmitVerification && !['suspended','archived'].includes(context.profileState);
  return <>
    {step === 1 && <fieldset className="profile-form-fields" disabled={disabled || !canEdit}><ProfileSection title={employerSteps[0]}><TextField title="Organizacijos pavadinimas" value={draft.name} maxLength={200} onChange={v => onChange({ name: v })} /><p className="profile-helper">Šį pavadinimą matys kandidatai.</p><SelectField title="Organizacijos tipas" value={draft.type} options={organizationTypes} onChange={onTypeChange} />{draft.type === 'other' && <TextField title="Organizacijos tipo pavadinimas" value={draft.typeOther} maxLength={200} onChange={v => onChange({ typeOther: v })} />}<TextEntries title="Miestai" values={draft.cities} limit={100} onChange={v => onChange({ cities: v })} /></ProfileSection></fieldset>}
    {step === 2 && <><p className="profile-notice">Šie duomenys privatūs. Juridiniai duomenys, atstovo vardas, pavardė ir kontaktinis telefonas kandidatams nerodomi.</p><fieldset className="profile-form-fields" disabled={disabled || !canEdit}><ProfileSection title="Juridiniai duomenys"><EmployerLegalFields value={draft} onChange={onChange} locked={context.verification.identityApproved} />{context.verification.identityApproved && <button type="button" className="profile-button secondary" onClick={onLegalChange}>Prašyti pakeisti</button>}</ProfileSection></fieldset><fieldset className="profile-form-fields" disabled={disabled || (!canEdit && !canRepresentative)}><ProfileSection title="Organizacijos atstovas"><EmployerRepresentativeFields value={draft} onChange={onChange} /></ProfileSection></fieldset></>}
    {step === 3 && <><p className="profile-intro">Ši dalis neprivaloma. 70 % pakanka aktyviam viešam profiliui.</p><fieldset className="profile-form-fields" disabled={disabled || !canEdit}><details className="employer-panel" open><summary>Apie organizaciją</summary><div className="profile-field"><label htmlFor={descriptionId}>Organizacijos aprašymas</label><textarea id={descriptionId} value={draft.description} maxLength={1500} onChange={e => onChange({ description: e.target.value })} /><span className="profile-counter">{draft.description.length} / 1500</span></div></details></fieldset><details className="employer-panel"><summary>Logotipas ir viršelio nuotrauka</summary>{media}</details><fieldset className="profile-form-fields" disabled={disabled || !canEdit}><details className="employer-panel"><summary>Organizacijos veikla</summary>{draft.type ? <EmployerActivityFields draft={draft} onChange={onChange} /> : <p>Pirmiausia pasirinkite organizacijos tipą pagrindiniuose duomenyse.</p>}</details><details className="employer-panel"><summary>Ką siūlome darbuotojams</summary><MultiField title="Darbuotojams siūlome" value={draft.benefits} options={benefitOptions} compact={false} onChange={v => onChange({ benefits: v })} /><TextEntries title="Kiti privalumai" values={draft.customBenefits} limit={120} maximum={10} onChange={v => onChange({ customBenefits: v })} /></details><details className="employer-panel"><summary>Vieši kontaktai ir papildoma informacija</summary><p className="profile-helper">Užpildyti kontaktai bus matomi viešame organizacijos profilyje.</p><TextField title="Interneto svetainė" type="url" optional value={draft.website} maxLength={2048} onChange={v => onChange({ website: v })} /><div className="profile-grid"><TextField title="Viešas telefonas" type="tel" optional value={draft.publicPhone} maxLength={40} onChange={v => onChange({ publicPhone: v })} /><TextField title="Viešas el. paštas" type="email" optional value={draft.publicEmail} maxLength={254} onChange={v => onChange({ publicEmail: v })} /></div>{(['facebookUrl','instagramUrl','linkedinUrl'] as const).map((key, i) => <TextField key={key} title={['Facebook','Instagram','LinkedIn'][i]} type="url" optional value={draft[key]} maxLength={2048} onChange={v => onChange({ [key]: v })} />)}<SelectField title="Komandos dydis" value={draft.employeeSize} options={employeeSizes} onChange={v => onChange({ employeeSize: v })} /></details></fieldset></>}
  </>;
}
