'use client';
import { useId, useRef } from 'react';
import { MultiField, ProfileSection, SelectField, TextField } from './ProfileFields';
import { benefitOptions, employeeSizes, hasDuplicates, organizationCatalogs as c, organizationTypes, type Draft } from '@/lib/organizations/frontend';
import type { OrganizationContext } from '@/lib/organizations/contracts';

/** Native disclosure/radios keep long selected labels readable without truncation. */
export function EmployerChoice({ title, value, options, onChange, disabled = false, allowEmpty = true }: { title: string; value: string; options: { code: string; label_lt: string }[]; onChange: (value: string) => void; disabled?: boolean; allowEmpty?: boolean }) {
  const id = useId(), disclosure = useRef<HTMLDetailsElement>(null);
  const choices = allowEmpty ? [{ code: '', label_lt: 'Nepasirinkta' }, ...options] : options;
  return <div className="profile-field employer-choice" data-title={title}><span id={id}>{title}</span><details ref={disclosure}><summary aria-labelledby={id + ' ' + id + '-value'} aria-disabled={disabled} onClick={e => { if (disabled) e.preventDefault(); }}><span id={id + '-value'}>{choices.find(o => o.code === value)?.label_lt || 'Nepasirinkta'}</span></summary><fieldset disabled={disabled}><legend className="visually-hidden">{title}</legend>{choices.map(o => <label key={o.code}><input type="radio" name={id} checked={o.code === value} onChange={() => { if (disclosure.current) { disclosure.current.open = false; disclosure.current.querySelector('summary')?.focus(); } onChange(o.code); }} /><span>{o.label_lt}</span></label>)}</fieldset></details></div>;
}

function PanelSummary({ title, summary }: { title: string; summary: string }) {
  return <summary><span className="employer-panel-title">{title}</span><span className="employer-panel-status">{summary || 'Nepapildyta · Neprivaloma'}</span></summary>;
}

export function TextEntries({ title, values, onChange, limit = 200, maximum }: { title: string; values: string[]; onChange: (values: string[]) => void; limit?: number; maximum?: number }) {
  const duplicate = hasDuplicates(values.map(v => v.trim()).filter(Boolean));
  return <fieldset className="profile-multi employer-entries"><legend>{title}</legend>{values.map((value, i) => <div className="employer-entry" key={i}><TextField title={`${title} ${i + 1}`} value={value} error={duplicate && value.trim() ? 'Pašalinkite pasikartojančias reikšmes.' : undefined} maxLength={limit} onChange={v => onChange(values.map((old, n) => n === i ? v : old))} /><button className="profile-button danger" type="button" aria-label={`Pašalinti: ${title} ${i + 1}`} onClick={() => onChange(values.filter((_, n) => n !== i))}>Pašalinti</button></div>)}<button type="button" className="profile-button secondary" disabled={maximum !== undefined && values.length >= maximum} onClick={() => onChange([...values, ''])}>{title === 'Miestai' ? 'Pridėti miestą' : 'Pridėti'}</button></fieldset>;
}
export function EmployerLegalFields({ value, onChange, locked = false }: { value: Pick<Draft, 'legalName' | 'legalForm' | 'legalCode'>; onChange: (patch: Partial<Draft>) => void; locked?: boolean }) {
  const form = c.legalForms.find(([code]) => code === value.legalForm);
  if (locked) return <><dl className="employer-legal-values"><div><dt>Juridinis pavadinimas</dt><dd>{value.legalName || 'Nepateikta'}</dd></div><div><dt>Teisinė forma</dt><dd>{String(form?.[1] || 'Nepateikta')}</dd></div><div><dt>Juridinio asmens kodas</dt><dd>{value.legalCode || 'Nepateikta'}</dd></div></dl><p className="profile-helper">Šie duomenys patikrinti.</p></>;
  return <><TextField title={['natural_person','individual_activity'].includes(value.legalForm) ? 'Juridinis pavadinimas / vardas ir pavardė' : 'Juridinis pavadinimas'} value={value.legalName} maxLength={200} readOnly={locked} onChange={v => onChange({ legalName: v })} /><SelectField title="Teisinė forma" options={c.legalForms.map(([code, label]) => ({ code: String(code), label_lt: String(label) }))} value={value.legalForm} disabled={locked} onChange={v => onChange({ legalForm: v })} /><TextField title="Juridinio asmens kodas" optional={form?.[2] === false} value={value.legalCode} maxLength={64} readOnly={locked} onChange={v => onChange({ legalCode: v })} /></>;
}
export function EmployerRepresentativeFields({ value, onChange }: { value: Pick<Draft, 'firstName' | 'lastName' | 'capacity' | 'privatePhone'>; onChange: (patch: Partial<Draft>) => void }) {
  return <><div className="profile-grid"><TextField title="Vardas" value={value.firstName} maxLength={100} onChange={v => onChange({ firstName: v })} /><TextField title="Pavardė" value={value.lastName} maxLength={100} onChange={v => onChange({ lastName: v })} /></div><TextField title="Atstovavimo pagrindas / pareigos" value={value.capacity} maxLength={200} onChange={v => onChange({ capacity: v })} /><TextField title="Kontaktinis telefonas" type="tel" value={value.privatePhone} maxLength={40} onChange={v => onChange({ privatePhone: v })} /><p className="profile-helper">Viešai nerodomas.</p></>;
}
export function EmployerActivityFields({ draft, onChange }: { draft: Draft; onChange: (patch: Partial<Draft>) => void }) {
  const groups = c.groups.filter(g => g.type === draft.type).sort((a, b) => a.order - b.order);
  return <>{groups.map(g => {
    const stored = draft.groups.find(value => value.group_code === g.code) ?? { group_code: g.code, options: [], custom: [] };
    const update = (patch: Partial<typeof stored>) => onChange({ groups: [...draft.groups.filter(value => value.group_code !== g.code), { ...stored, ...patch }] });
    const choices = c.options.filter(o => o.type === draft.type && o.group === g.code).sort((a, b) => a.order - b.order).map(o => ({ code: o.code, label_lt: o.label }));
    return <div key={`${draft.type}:${g.code}`} className="employer-activity-group">{g.kind === 'choice' && <><p className="profile-helper employer-selected-count">{stored.options.length} pasirinkta</p><MultiField title={g.label} value={stored.options} options={choices} compact={false} onChange={v => update({ options: v, custom: v.includes('other') ? stored.custom : [] })} /></>}{(g.kind === 'text' || stored.options.includes('other')) && <TextEntries title={g.kind === 'text' ? g.label : `${g.label}: kita`} values={stored.custom} onChange={v => update({ custom: v })} />}</div>;
  })}</>;
}
export default function EmployerProfileFields({ step, draft, context, disabled, onChange, onTypeChange, onLegalChange, media }: { step: number; draft: Draft; context: OrganizationContext; disabled: boolean; onChange: (patch: Partial<Draft>) => void; onTypeChange: (value: string) => void; onLegalChange: () => void; media: React.ReactNode }) {
  const descriptionId = useId();
  const canEdit = context.capabilities.canEditProfile;
  const canRepresentative = context.capabilities.canSubmitVerification && !['suspended','archived'].includes(context.profileState);
  const mediaCount = (['logo','cover'] as const).filter(kind => context.organization.media?.[kind]).length;
  const benefitsCount = draft.benefits.length + draft.customBenefits.filter(v => v.trim()).length;
  const contacts = [draft.publicEmail && 'El. paštas', draft.website && 'svetainė', draft.publicPhone && 'telefonas'].filter(Boolean).join(' ir ');
  return <>
    {step === 1 && <fieldset className="profile-form-fields employer-basic-fields" disabled={disabled || !canEdit}><TextField title="Organizacijos pavadinimas" value={draft.name} maxLength={200} onChange={v => onChange({ name: v })} /><p className="profile-helper">Šį pavadinimą matys kandidatai.</p><EmployerChoice title="Organizacijos tipas" value={draft.type} options={organizationTypes} onChange={onTypeChange} disabled={disabled || !canEdit} />{draft.type === 'other' && <TextField title="Organizacijos tipo pavadinimas" value={draft.typeOther} maxLength={200} onChange={v => onChange({ typeOther: v })} />}<TextEntries title="Miestai" values={draft.cities} limit={100} onChange={v => onChange({ cities: v })} /></fieldset>}
    {step === 2 && <><p className="profile-notice employer-private-notice">Šie duomenys privatūs. Kandidatams nerodomi.</p><fieldset className="profile-form-fields" disabled={disabled || !canEdit}><ProfileSection title="Juridiniai duomenys"><EmployerLegalFields value={draft} onChange={onChange} locked={context.verification.identityApproved} />{context.verification.identityApproved && <button type="button" className="profile-button secondary" onClick={onLegalChange}>Prašyti pakeisti</button>}</ProfileSection></fieldset><fieldset className="profile-form-fields" disabled={disabled || (!canEdit && !canRepresentative)}><ProfileSection title="Organizacijos atstovas"><EmployerRepresentativeFields value={draft} onChange={onChange} /></ProfileSection></fieldset></>}
    {step === 3 && <><p className="profile-intro">Neprivaloma. 70 % pakanka aktyviam viešam profiliui.</p>
      <fieldset className="profile-form-fields" disabled={disabled || !canEdit}><details className="employer-panel" open><PanelSummary title="Apie organizaciją" summary={draft.description.trim() ? 'Aprašymas pateiktas' : ''} /><div className="employer-panel-body"><div className="profile-field"><label htmlFor={descriptionId}>Organizacijos aprašymas</label><textarea id={descriptionId} value={draft.description} maxLength={1500} onChange={e => onChange({ description: e.target.value })} /><span className="profile-counter">{draft.description.length} / 1500</span></div></div></details></fieldset>
      <details className="employer-panel"><PanelSummary title="Logotipas ir viršelio nuotrauka" summary={mediaCount ? `${mediaCount} ${mediaCount === 1 ? 'vaizdas' : 'vaizdai'}` : ''} /><div className="employer-panel-body"><p className="profile-helper">Vaizdų pakeitimai išsaugomi iš karto.</p>{media}</div></details>
      <fieldset className="profile-form-fields" disabled={disabled || !canEdit}>
        <details className="employer-panel"><PanelSummary title="Organizacijos veikla" summary={draft.groups.some(g => g.options.length || g.custom.some(v => v.trim())) ? 'Veiklos duomenys pateikti' : ''} /><div className="employer-panel-body">{draft.type ? <EmployerActivityFields draft={draft} onChange={onChange} /> : <p>Pirmiausia pasirinkite organizacijos tipą pagrindiniuose duomenyse.</p>}</div></details>
        <details className="employer-panel"><PanelSummary title="Ką siūlome darbuotojams" summary={benefitsCount ? `${benefitsCount} ${benefitsCount === 1 ? 'privalumas' : 'privalumai'}` : ''} /><div className="employer-panel-body"><MultiField title="Darbuotojams siūlome" value={draft.benefits} options={benefitOptions} compact={false} onChange={v => onChange({ benefits: v })} /><TextEntries title="Kiti privalumai" values={draft.customBenefits} limit={120} maximum={10} onChange={v => onChange({ customBenefits: v })} /></div></details>
        <details className="employer-panel"><PanelSummary title="Vieši kontaktai ir papildoma informacija" summary={contacts || (draft.employeeSize || draft.facebookUrl || draft.instagramUrl || draft.linkedinUrl ? 'Informacija pateikta' : '')} /><div className="employer-panel-body"><p className="profile-helper">Užpildyti kontaktai bus matomi viešame organizacijos profilyje.</p><TextField title="Interneto svetainė" type="url" optional value={draft.website} maxLength={2048} onChange={v => onChange({ website: v })} /><div className="profile-grid"><TextField title="Viešas telefonas" type="tel" optional value={draft.publicPhone} maxLength={40} onChange={v => onChange({ publicPhone: v })} /><TextField title="Viešas el. paštas" type="email" optional value={draft.publicEmail} maxLength={254} onChange={v => onChange({ publicEmail: v })} /></div>{(['facebookUrl','instagramUrl','linkedinUrl'] as const).map((key, i) => <TextField key={key} title={['Facebook','Instagram','LinkedIn'][i]} type="url" optional value={draft[key]} maxLength={2048} onChange={v => onChange({ [key]: v })} />)}<SelectField title="Komandos dydis" value={draft.employeeSize} options={employeeSizes} onChange={v => onChange({ employeeSize: v })} /></div></details>
      </fieldset></>}
  </>;
}
