'use client';
import { useState } from 'react';
import type { SpecialistStep3 } from '@/lib/profiles/contracts';
import { groupLabels, label, standardLevels, studentLevels, type ProfileCatalogs, type ProfileStep3Draft } from '@/lib/profiles/view-model';
import { ChoiceField, MultiField, ProfileSection, SelectField, TextField } from './ProfileFields';

export default function ProfileCompetencies({ role, catalogs: c, value: v, onChange, errors }: { role: string | null; catalogs: ProfileCatalogs; value: ProfileStep3Draft; onChange: (v: ProfileStep3Draft) => void; errors: Record<string, string> }) {
  const matrix = c.competencies.filter(o => o.professional_role_code === role), levels = role === 'veterinary_student' ? studentLevels : standardLevels;
  const groups = Array.from(new Set(matrix.map(o => o.category))), [open, setOpen] = useState<string[]>(groups.slice(0, 1));
  const autonomy = c.autonomy.filter(o => o.professional_role_code === role), development = c.development.filter(o => o.professional_role_code === role);
  const custom = v.custom_competencies ?? [];
  return <><ProfileSection title="Profesija"><p className="profile-profession-value">{label(c.roles, role)}</p></ProfileSection>
    {!role && <p className="profile-helper">Pirmiausia išsaugokite profesijos pasirinkimą pagrindiniuose duomenyse.</p>}
    {groups.map(group => { const items = matrix.filter(o => o.category === group), expanded = open.includes(group), count = items.filter(o => v.competencies?.some(r => r.competency_code === o.code && r.level)).length; return <section key={group} className={'profile-competency-group ' + (expanded ? 'expanded' : '')}>
      <h2 className="profile-desktop-group">{groupLabels[group] ?? 'Kompetencijos'}</h2><button type="button" className="profile-accordion" aria-expanded={expanded} aria-controls={'competencies-' + group} onClick={() => setOpen(expanded ? open.filter(g => g !== group) : [...open, group])}><span><strong>{groupLabels[group] ?? 'Kompetencijos'}</strong><small>Atsakyta: {count} iš {items.length}</small></span><span aria-hidden="true">{expanded ? '⌃' : '⌄'}</span></button>
      <div className="profile-competency-items" id={'competencies-' + group}>{items.map(o => <div className="profile-competency-row" key={o.code}><SelectField title={o.label_lt} value={v.competencies?.find(r => r.competency_code === o.code)?.level} options={levels} onChange={s => onChange({ ...v, competencies: [...(v.competencies ?? []).filter(r => r.competency_code !== o.code), { competency_code: o.code, level: (s || null) as NonNullable<SpecialistStep3['competencies']>[number]['level'] }] })} /></div>)}</div>
    </section>; })}
    {role === 'other_veterinary_specialty' && <ProfileSection title="Kompetencijos">{custom.map((item, i) => <div key={i} className="profile-custom-competency"><TextField title="Kompetencijos pavadinimas" value={item.name} maxLength={200} error={errors['custom-' + i]} onChange={s => onChange({ ...v, custom_competencies: custom.map((r, n) => n === i ? { ...r, name: s } : r) })} /><SelectField title="Kompetencijos lygis" value={item.level} options={levels} onChange={s => onChange({ ...v, custom_competencies: custom.map((r, n) => n === i ? { ...r, level: s as typeof r.level } : r) })} /><button type="button" className="profile-button danger" onClick={() => onChange({ ...v, custom_competencies: custom.filter((_, n) => n !== i) })}>Pašalinti</button></div>)}<button type="button" className="profile-button secondary" disabled={custom.length >= 5} onClick={() => onChange({ ...v, custom_competencies: [...custom, { name: '', level: '' }] })}>Pridėti kompetenciją</button><p className="profile-helper">1 kompetencija – +10 %, 2 kompetencijos – +20 %, 3 ir daugiau – +30 %.</p></ProfileSection>}
    {autonomy.length > 0 && <ProfileSection title="Bendras savarankiškumas klinikinėje praktikoje" optional><ChoiceField title="Bendras savarankiškumas klinikinėje praktikoje" value={v.autonomy_code} options={autonomy} onChange={s => onChange({ ...v, autonomy_code: s })} />{v.autonomy_code && <button type="button" className="profile-text-button" onClick={() => onChange({ ...v, autonomy_code: null })}>Išvalyti pasirinkimą</button>}</ProfileSection>}
    {development.length > 0 && <ProfileSection title="Kur norėtumėte tobulėti?" optional><MultiField title="Kur norėtumėte tobulėti?" value={v.development_areas ?? []} options={development} onChange={s => onChange({ ...v, development_areas: s })} /></ProfileSection>}
    {role === 'other_veterinary_specialty' && <ProfileSection title="Kur norėtumėte tobulėti?" optional>{(v.custom_development ?? []).map((s, i) => <div className="profile-custom-development" key={i}><TextField title="Tobulėjimo sritis" value={s} maxLength={200} error={errors['development-' + i]} onChange={s => onChange({ ...v, custom_development: v.custom_development?.map((r, n) => n === i ? s : r) })} /><button type="button" className="profile-button danger" onClick={() => onChange({ ...v, custom_development: v.custom_development?.filter((_, n) => n !== i) })}>Pašalinti</button></div>)}<button type="button" className="profile-button secondary" onClick={() => onChange({ ...v, custom_development: [...(v.custom_development ?? []), ''] })}>Pridėti tobulėjimo sritį</button></ProfileSection>}
  </>;
}
